version: '3'

services:
    backend:
        build: ./backend
        env_file: .env
        volumes:
            - data:/data
        ports:
            - 80:5000

    worker:
        build: ./worker
        env_file: .env
        volumes:
            - data:/data

    redis:
        image: redis:latest
        volumes:
            - db-data:/data

volumes:
    data:
    db-data:
